### ISSUE TITLE
Cannot increase weighting of likelihood in `examples/Shin_PLOS2019`

### ISSUE THREAD

**Issue by paulflang** [paulflang/SBML2JuliaMP#11]
In the `petab_suite` branch, when I reduce the measurement error​ (`examples/Shin_PLOS2019/julia_code.jl` line 252) from `sigma = 1.0` to 0.1, 0.5 or 0.8, JuMP either exits with `Restoration failed!` or `Maximum number of iterations exceeded`. Any ideas how to solve that?

**Comment by paulflang** [comment]
This issue refers to commit ff8dfac9cc935a9abd98fae949b2b5b7bb26d4ea

**Comment by sshin23** [comment]
Seems to work if the linear solver is changed to ma27 or ma97. This is a bit mysterious behavior, but sometimes using a different linear solver fixes the issue.

**Comment by paulflang** [comment]
Thanks for the hint. I tried MA27, and it works without restoration error, but it estimates most if not all parameters to be zero. See for instance this image for the growth of species one alone:
![image](https://user-images.githubusercontent.com/47160416/97114909-981f8a80-16f3-11eb-95ec-776c0196d41f.png)

Here is the code I used to run it:
```Python
import os
import pandas as pd
import pickle
import pkg_resources
import re
import shutil
import tempfile
import unittest
from SBML2JuliaMP import core
import importlib
importlib.reload(core)

FIXTURES = os.path.join('/media/sf_DPhil_Project/Project07_Parameter Fitting/df_software',
    'SBML2JuliaMP', 'examples')
PETAB_YAML = os.path.join(FIXTURES, 'Shin_PLOS2019', 'Shin_PLOS2019.yaml')

problem = core.SBML2JuliaMPProblem(PETAB_YAML, optimizer_options={'linear_solver': 'MA27'}, n_starts=1)
problem.insert_custom_code({'    # Model initial assignments': '    # Custom code\n    bindings = [Int(i) for i in range(13, stop=210, length=198) if mod(i,3) != 0]\n    @constraint(m, [j in bindings], A[j, 3] == 20*A[j+1, 1])\n    @constraint(m, [j in bindings], B[j, 3] == 20*B[j+1, 1])\n\n    # Model initial assignments'})
problem.write_jl_file()
problem.optimize()
problem.plot_results('c_1', path='plot.pdf')
problem.write_results()
problem.write_optimized_parameter_table()
```
Here is the generated jl_file: 
[julia_code.txt](https://github.com/paulflang/SBML2JuliaMP/files/5435370/julia_code.txt)

When fitting, I noticed the following messages:
```
Scaling factors are invalid - setting them all to 1.
MA27BD returned iflag=-4 and requires more memory.
 Increase liw from 28533500 to 57067000 and la from 32335112 to 71996772 and factorize again.
```

**Comment by paulflang** [comment]
Oh. Wait a sec. Need to check sth.

**Comment by paulflang** [comment]
I am trying MA97 now.

**Comment by paulflang** [comment]
MA97 exits with
`EXIT: Maximum Number of Iterations Exceeded.`

**Comment by paulflang** [comment]
Works now. Previously it appeared that either the weights on the priors compared to the likelihood was too strong, or the restoration failed. I do not know what exactly went wrong (maybe an unfortunate combination of solvers and priors), but in commit 07f2a73eceaf41756aa9be27ce89e83c0e7cee6e everything works fine now. The fits actually look pretty good, but this because I set the measurement noise quite low (`0.05`) and the standard deviation of the parameter prior quite high (`3`).
